id: P6706F664
initial_creation_type: input
source_metadata:
  Title: Ālambanaparīkṣāvṛttiḥ
  Editor: Shastri, N. .Aiyaswami
  Publisher: The Adyar Library
  Place of Publication: Madras
  Year: '1942'
  Ālambanaparīkṣāvṛttiḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:47:41.631833'
last_modified_at: '2022-03-08T16:47:41.631843'
